# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playlistDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_playlistDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(602, 674)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        Dialog.setStyleSheet("background-color:#212121;")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(60, 30))
        self.frame.setMaximumSize(QtCore.QSize(1666666, 30))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("background-color:#212121;\n"
"border-width:3px;\n"
"border-style:solid;\n"
"border-color:#2c2c2c;\n"
"border-bottom:None;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(110, 0, 10, 5)
        self.horizontalLayout.setSpacing(60)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hotbar_mouv = QtWidgets.QFrame(self.frame)
        self.hotbar_mouv.setStyleSheet("background-color: #2c2c2c;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"border:None;")
        self.hotbar_mouv.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hotbar_mouv.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hotbar_mouv.setObjectName("hotbar_mouv")
        self.horizontalLayout.addWidget(self.hotbar_mouv)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(40, 25))
        self.frame_2.setMaximumSize(QtCore.QSize(40, 25))
        self.frame_2.setStyleSheet("border:None;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.closeButon = QtWidgets.QPushButton(self.frame_2)
        self.closeButon.setMinimumSize(QtCore.QSize(40, 20))
        self.closeButon.setMaximumSize(QtCore.QSize(40, 20))
        self.closeButon.setStyleSheet("QPushButton { background: transparent; border:0px; } \n"
"QPushButton:hover {background-color:red;color:white;border-radius:0px}")
        self.closeButon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/croce.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButon.setIcon(icon)
        self.closeButon.setObjectName("closeButon")
        self.horizontalLayout_3.addWidget(self.closeButon)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_7.addWidget(self.frame)
        self.frame10 = QtWidgets.QFrame(Dialog)
        self.frame10.setStyleSheet("background-color:#212121;\n"
"border-width:3px;\n"
"border-style:solid;\n"
"border-color:#2c2c2c;\n"
"border-top:None;")
        self.frame10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame10.setObjectName("frame10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame10)
        self.verticalLayout_5.setContentsMargins(80, 32, 80, 60)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frame10)
        self.frame_3.setStyleSheet("background-color: #2c2c2c ; \n"
"border-radius : 20px;\n"
"border:None;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.frame_3)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_10.setContentsMargins(70, 20, 70, -1)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.albumLineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.albumLineEdit.setMinimumSize(QtCore.QSize(200, 40))
        self.albumLineEdit.setMaximumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.albumLineEdit.setFont(font)
        self.albumLineEdit.setStyleSheet("QLineEdit { border-radius : 10px ;\n"
" border : 1px solid gray ; \n"
"background-color:#2c2c2c ; \n"
"color:gray;}")
        self.albumLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.albumLineEdit.setObjectName("albumLineEdit")
        self.verticalLayout_10.addWidget(self.albumLineEdit)
        self.artistLineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.artistLineEdit.setMinimumSize(QtCore.QSize(200, 40))
        self.artistLineEdit.setMaximumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.artistLineEdit.setFont(font)
        self.artistLineEdit.setStyleSheet("QLineEdit { border-radius : 10px ;\n"
" border : 1px solid gray ; \n"
"background-color:#2c2c2c ; \n"
"color:gray;}")
        self.artistLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.artistLineEdit.setObjectName("artistLineEdit")
        self.verticalLayout_10.addWidget(self.artistLineEdit)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 400, 312))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.L = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.L.setContentsMargins(30, 20, 30, 20)
        self.L.setSpacing(4)
        self.L.setObjectName("L")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_9.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.frame_3)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.envoieButton = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.envoieButton.sizePolicy().hasHeightForWidth())
        self.envoieButton.setSizePolicy(sizePolicy)
        self.envoieButton.setMinimumSize(QtCore.QSize(250, 40))
        self.envoieButton.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.envoieButton.setFont(font)
        self.envoieButton.setStyleSheet("QPushButton { border-radius : 5px ; border: 1px #1f528d ; background-color: #1f528d ; color:lightgray }")
        self.envoieButton.setObjectName("envoieButton")
        self.horizontalLayout_4.addWidget(self.envoieButton)
        self.verticalLayout_9.addWidget(self.widget_3)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.verticalLayout_7.addWidget(self.frame10)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.albumLineEdit.setPlaceholderText(_translate("Dialog", "Album de la Musique :"))
        self.artistLineEdit.setPlaceholderText(_translate("Dialog", "Artiste de la Musique"))
        self.envoieButton.setText(_translate("Dialog", "Envoyer"))
